### ISSUE TITLE
Large number not parsed well.

### ISSUE THREAD

**Issue by docktermj** [Senzing/mock-data-generator#40]
This was seen when `record_max` was `1000000`.

```console
Traceback (most recent call last):

  File "/app/mock-data-generator.py", line 1919, in <module>
    globals()[subcommand_function_name](args)

  File "/app/mock-data-generator.py", line 1494, in do_url_to_rabbitmq
    publisher = RabbitMQAsyncPublisher(args)

  File "/app/mock-data-generator.py", line 1559, in __init__
    config = get_configuration(args)

  File "/app/mock-data-generator.py", line 525, in get_configuration
    result[integer] = int(integer_string) ValueError: invalid literal for int() with base 10: '1e+06'
```

**Comment by docktermj** [comment]
Actually a Helm issue:

```
helm template  \
    --values ~/senzing.git/kubernetes-demo/helm-values/mock-data-generator-rabbitmq.yaml \
    ~/senzing.git/charts/charts/senzing-mock-data-generator/senzing-mock-data-generator
```
Shows this: 

```
---
# Source: senzing-mock-data-generator/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-senzing-mock-data-generator
spec:
  template:
    spec:
      containers:
        - name: senzing-mock-data-generator
          image: data.dockter.com:5000/senzing/mock-data-generator:latest
          imagePullPolicy: Always
          env:
            - name: "SENZING_INPUT_URL"
              value: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
            - name: "SENZING_KAFKA_BOOTSTRAP_SERVER"
              value: "my-kafka-kafka:9092"
            - name: "SENZING_KAFKA_TOPIC"
              value: "senzing-kafka-topic"
            - name: "SENZING_RABBITMQ_HOST"
              value: "my-rabbitmq"
            - name: "SENZING_RABBITMQ_PASSWORD"
              value: "passw0rd"
            - name: "SENZING_RABBITMQ_QUEUE"
              value: "senzing-rabbitmq-queue"
            - name: "SENZING_RABBITMQ_USERNAME"
              value: "user"
            - name: "SENZING_RECORD_MAX"
              value: "1e+06"
            - name: "SENZING_RECORD_MONITOR"
              value: "1000"
            - name: "SENZING_SUBCOMMAND"
              value: "url-to-rabbitmq"
      restartPolicy: Never
# --- Standard suffix ---
      imagePullSecrets:
        - name: data.dockter.com:5000-secret
        
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
```
Notice the value of `SENZING_RECORD_MAX`.  ...which causes the problem.
